!function(){"use strict";class t{constructor(){this.settings={lazy:{loadPrevNext:!0},loop:!0,speed:800,navigation:{nextEl:".progress-button-next",prevEl:".progress-button-prev"},pagination:{el:".progress-pagination",clickable:!0},breakpoints:{320:{spaceBetween:10},577:{spaceBetween:20},993:{spaceBetween:24},1201:{spaceBetween:32}}},this.progressLeftEl=document.querySelector(".progress__left .swiper-wrapper"),this.progressWrapEl=document.querySelector(".progress__wrap .swiper-wrapper"),this.pathToTownshipsProgressImages="assets/img/dist/townships/progress"}addTabsIntoPage(e,s){let t="";for(var r of e)r.townshipId==s&&(t+=this.getTabMarkup(r));this.progressLeftEl.insertAdjacentHTML("beforeend",t)}getTabMarkup(e){return`
			<div class="swiper-slide tab__slide">
						<button type="button" class="progress__tab" data-tab="${e.date}">${e.date}</button>
					</div>
			`}renderCardsProgress(s,t){var e=document.querySelector(".progress__tab").textContent;this.insertCardsProgressIntoPage(s,t,e),this.changeStyleBtn(document.querySelector(".progress__tab"));let r=new Swiper(".progress-slider",this.settings);document.querySelectorAll(".progress__tab").forEach(e=>{e.addEventListener("click",()=>{this.insertCardsProgressIntoPage(s,t,e.dataset.tab),this.changeStyleBtn(e),r.destroy(),r=new Swiper(".progress-slider",this.settings)})})}changeStyleBtn(e){document.querySelector(".progress__tab.active")&&document.querySelector(".progress__tab.active").classList.remove("active"),e.classList.add("active")}insertCardsProgressIntoPage(e,s,t){let r="";for(var a of e)if(a.townshipId==s&&a.date==t)for(let e=0;e<a.images.length;e++)r+=this.getCardsProgressMarkup(a,a.images[e],a.imagesMiddle[e]);this.progressWrapEl.textContent="",this.progressWrapEl.insertAdjacentHTML("beforeend",r)}getCardsProgressMarkup(e,s,t){return`<div class="swiper-slide progress__slide">
				<picture class="progress__photo">
					<source data-srcset="${this.pathToTownshipsProgressImages}/${s}" media="(min-width: 576px)" width="994" height="596">
					<source data-srcset="${this.pathToTownshipsProgressImages}/${t}" media="(min-width: 0)" width="556" height="334">
					<img class="swiper-lazy" data-src="${this.pathToTownshipsProgressImages}/${t}" alt="${e.date}" width="556" height="334">
				</picture>
			</div>`}}window.addEventListener("load",()=>{var e=new t,s=location.hash.replace(/#/,"");e.addTabsIntoPage(constructions,s),e.renderCardsProgress(constructions,s)})}();